### ISSUE TITLE
Main game loop screen

### ISSUE THREAD

**Issue by wolkonowski** [MobileApps23-KebalandTeam/Kebaland#11]
slicing kebab, pouring souce, horizontal swipe indicates next/previous ingredient, etc

**Comment by ksurdyk1** [comment]
Screen description:
https://docs.google.com/document/d/156BCLyK1vumdWf9wkytLYcaMQ6fPR58uuc6M67CzaiU/edit#heading=h.ax01vt9qi9kc

Whole game flow:
https://docs.google.com/document/d/156BCLyK1vumdWf9wkytLYcaMQ6fPR58uuc6M67CzaiU/edit#heading=h.ph2xuqbhjtyf

**Comment by kurbisz** [comment]
Pozostało:
- [x] sprawdzanie co jest na talerzu
- [x] przydzielanie różnych warzyw (dodatków) na różne sloty
- [x] zakończenie sesji (panel końcowy + przerzucenie do poprzedniego menu)
- [x] informacja o oddaniu zamówienia/błędnym zamówieniu, przekierowanie na pierwszy ekran i wyczyszczenie odpowiednich zmiennych itp
- [x] naprawa wyświetlania (skalowania) składników na kebabie
- [x] przeniesienie paska przy laniu sosów + naprawa skalowania
- [x] dodanie minimalnej ilości punktów + w zależności od tego zmiana końcowego menu
- [x] podłączenie tego menu pod mapę + odłączenie go z głównego menu
- [x] zostawienie mięsa po przejściu na kolejną część menu (i po oddaniu zamówienia)
- [x] naprawa skalowania na różnych telefonach
- [ ] zmiana grafiki
